EXCEL_FILE = "timetracker.xlsx"
TARGET_HOURS = 7.4
LOG_SHEET = "Time Log"
SUM_SHEET = "Summary"

# Colours
C_HEADER = "2C5F8A"
C_HEADER_SUM = "1A4A6B"
C_ALT = "EAF2FB"
C_WHITE = "FFFFFF"
C_OVER = "D6F0D6"
C_UNDER = "FAE3E3"
C_TODAY = "FFF8DC"
